/*
 * Bybit API
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.0.1
 * Contact: IT@bybit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bybit.sdk.api;

import com.bybit.sdk.model.LinearCancelOrderEnvelope;
import com.bybit.sdk.model.LinearCreateOrderEnvelope;
import com.bybit.sdk.model.LinearOrderCancel;
import com.bybit.sdk.model.LinearOrderCreate;
import com.bybit.sdk.model.LinearOrderReplace;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for LinearOrderApi
 */
@Ignore
public class LinearOrderApiTest {

    private final LinearOrderApi api = new LinearOrderApi();

    /**
     * Cancel Active Order
     *
     * This will cancel linear active order
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void linearOrderCancelTest() throws Exception {
        LinearOrderCancel body = null;
        LinearCancelOrderEnvelope response = api.linearOrderCancel(body);

        // TODO: test validations
    }
    /**
     * Create Active Order
     *
     * This will create linear order
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void linearOrderNewTest() throws Exception {
        LinearOrderCreate body = null;
        LinearCreateOrderEnvelope response = api.linearOrderNew(body);

        // TODO: test validations
    }
    /**
     * Replace Active Order
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void linearOrderReplaceTest() throws Exception {
        LinearOrderReplace body = null;
        LinearCreateOrderEnvelope response = api.linearOrderReplace(body);

        // TODO: test validations
    }
}
