/*
 * Bybit API
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.0.1
 * Contact: IT@bybit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bybit.sdk.api;

import java.math.BigDecimal;
import com.bybit.sdk.model.SpotCancelOrderEnvelope;
import com.bybit.sdk.model.SpotCreateOrderEnvelope;
import com.bybit.sdk.model.SpotGetOrderEnvelope;
import com.bybit.sdk.model.TimeInForceSpot;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for OrderApi
 */
@Ignore
public class OrderApiTest {

    private final OrderApi api = new OrderApi();

    /**
     * Cancel active order
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void orderCancelTest() throws Exception {
        String orderId = null;
        String orderLinkId = null;
        SpotCancelOrderEnvelope response = api.orderCancel(orderId, orderLinkId);

        // TODO: test validations
    }
    /**
     * Place active order
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void orderNewTest() throws Exception {
        String symbol = null;
        String side = null;
        String type = null;
        BigDecimal qty = null;
        BigDecimal price = null;
        TimeInForceSpot timeInForce = null;
        String orderLinkId = null;
        SpotCreateOrderEnvelope response = api.orderNew(symbol, side, type, qty, price, timeInForce, orderLinkId);

        // TODO: test validations
    }
    /**
     * Get active order
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void orderQueryTest() throws Exception {
        String orderId = null;
        String orderLinkId = null;
        SpotGetOrderEnvelope response = api.orderQuery(orderId, orderLinkId);

        // TODO: test validations
    }
}
