/*
 * Bybit API
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.0.1
 * Contact: IT@bybit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bybit.sdk.api;

import com.bybit.sdk.model.WalletBalanceEnvelope;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for WalletApi
 */
@Ignore
public class WalletApiTest {

    private final WalletApi api = new WalletApi();

    /**
     * get wallet balance info
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void walletGetBalanceTest() throws Exception {
        String coin = null;
        WalletBalanceEnvelope response = api.walletGetBalance(coin);

        // TODO: test validations
    }
}
